#!/usr/bin/env node
/**
 * Inlines the @font-face rules into index.html and preloads the critical faces.
 *
 * A <link> to fonts.googleapis.com costs a stylesheet round trip before the
 * browser even learns which font files it needs. Loading it asynchronously fixed
 * the render blocking but moved the problem: the faces then arrived after first
 * paint and the swap reflowed the text, which Lighthouse measured as ~0.15
 * layout shift on every other run.
 *
 * Inlining the rules means the font files are discovered in the first HTML
 * chunk, and preloading the three faces the first screen uses gets them in
 * flight immediately. The files themselves still come from Google's CDN.
 */
import { readFileSync, writeFileSync } from 'node:fs';

// Only the weights the components actually pair with each family. Every extra
// weight is another file competing for bandwidth before the text can settle.
const FAMILIES =
  'family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400;500;600;700&family=Plus+Jakarta+Sans:wght@600;700;800';
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36';
const KEEP = new Set(['latin', 'latin-ext']);
// What the hero paints with: body copy, the display heading, the mono labels.
const CRITICAL = [
  ['Inter', '400', 'latin'],
  ['Plus Jakarta Sans', '800', 'latin'],
  ['JetBrains Mono', '600', 'latin'],
];

const css = await (
  await fetch(`https://fonts.googleapis.com/css2?${FAMILIES}&display=swap`, { headers: { 'User-Agent': UA } })
).text();

const faces = [];
const preloads = [];
for (const [, subset, face] of css.matchAll(/\/\* ([\w-]+) \*\/\s*(@font-face \{[^}]+\})/g)) {
  if (!KEEP.has(subset)) continue;
  faces.push(face.replace(/\s+/g, ' ').replace('{ ', '{').replace(' }', '}'));

  const family = face.match(/font-family: '([^']+)'/)[1];
  const weight = face.match(/font-weight: (\d+)/)[1];
  if (CRITICAL.some(([f, w, s]) => f === family && w === weight && s === subset)) {
    preloads.push(
      `    <link rel="preload" as="font" type="font/woff2" crossorigin href="${face.match(/url\((https:[^)]+)\)/)[1]}" />`,
    );
  }
}

const block = [
  '    <!-- fonts:start — generated by scripts/gen-fonts.mjs, do not edit -->',
  ...preloads,
  '    <style>',
  ...faces.map((f) => `      ${f}`),
  '    </style>',
  '    <!-- fonts:end -->',
].join('\n');

const html = readFileSync('index.html', 'utf8');
const start = html.indexOf('    <!-- fonts:start');
const end = html.indexOf('<!-- fonts:end -->');
if (start === -1 || end === -1) throw new Error('index.html is missing the fonts:start / fonts:end markers');

writeFileSync('index.html', html.slice(0, start) + block + html.slice(end + '<!-- fonts:end -->'.length));
console.log(`[fonts]  ${faces.length} faces inlined, ${preloads.length} preloaded`);
